import { Header } from "@/components/header";
import { Layout } from "@/layout";
import { api } from "@/utils/api";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

type PageRoutes = {
  project: string;
  page: string;
};

export default function Page() {
  const router = useRouter();
  const { data: sessionData } = useSession();
  const { project: projectName, page: pageName } = router.query as PageRoutes;
  const {
    data: page,
    error,
    isError,
    isLoading,
  } = api.projects.getPageOfProject.useQuery({
    projectName,
    pageName,
  });

  if (!projectName || !pageName) return <div>invalid path</div>;
  if (!sessionData) return <div>not logged in</div>;
  if (isError) return <div>{error.message}</div>;
  if (isLoading || !page) return <div>loading</div>;

  return (
    <>
      <Head>
        <title>My projects</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        header={
          <Header
            item={`${projectName} 👉 ${pageName}`}
            user={sessionData.user}
          />
        }
        content={<div></div>}
      />
    </>
  );
}
