import { Header } from "@/components/header";
import { ViewList } from "@/components/view-list";
import { Layout } from "@/layout";
import { api } from "@/utils/api";
import { type Page } from "@/data/page";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { PageList } from "@/components/page-list";

type PageRoutes = {
  project: string;
  page: string;
};

export default function Page() {
  const router = useRouter();
  const { data: sessionData } = useSession();
  const { project: projectName, page: pagePath } = router.query as PageRoutes;
  const {
    data: page,
    error,
    isError,
    isLoading,
  } = api.projects.getPageOfProject.useQuery({
    projectName,
    pagePath,
  });

  if (!projectName || !pagePath) return <div>invalid path</div>;
  if (!sessionData) return <div>not logged in</div>;
  if (isError) return <div>{error.message}</div>;
  if (isLoading || !page) return <div>loading</div>;

  return (
    <>
      <Head>
        <title>My projects</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        header={
          <Header
            item={`${projectName} 👉 ${page.name}`}
            user={sessionData.user}
          />
        }
        sidebarLeft={
          <div className="flex h-full flex-col bg-slate-700">
            <div className="flex h-full flex-row">
              <ViewList activeView={"pages"} />
              <div className="flex h-full w-full flex-col justify-between bg-slate-700">
                <PageList projectName={projectName} pagePath={pagePath} />
              </div>
            </div>
            {/* <StatusBar /> */}
          </div>
        }
        content={<div></div>}
      />
    </>
  );
}
