name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run lint:types

      - name: Lint
        run: npm run lint:conventions

      - name: Find duplicates
        run: npm run lint:duplicates

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
