name: Linting

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Prepare environment
        run: npm ci

      - name: Typecheck
        run: npm run lint:types

      - name: Lint
        run: npm run lint:conventions

      - name: Find duplicates
        run: npm run lint:duplicates

      - name: Print Environment Variables
        run: echo $MY_ENV_VAR
